baseURL = "http://example.org/"
languageCode = "en-us"
title = "Stat 253 R Learning Site"

[params]
  copyright = "The Docsy Authors"
  privacy_policy = "https://policies.google.com/privacy"

[params.ui]
  sidebar_menu_compact = false
  breadcrumb_disable = false
  sidebar_search_disable = false
  navbar_logo = false
  footer_about_disable = false

[params.links]
  [[params.links.developer]]
    name = "GitHub"
    url = "https://github.com/YOUR-USERNAME/stat253-r-site"
    icon = "fab fa-github"
    desc = "Development takes place here!"

[module]
  [[module.imports]]
    path = "github.com/google/docsy"
    disable = false